title: Aryaman Gupta
description: Finance and consulting professional focused on investing, transactions and value creation.
url: "https://aryamangupta.co"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed

permalink: /writing/:title/
